# Generated by Django 5.2 on 2026-03-04 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.projecttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('SCOPE_IN_PROGRESS', 'Scope In Progress'), ('OUT_TO_BID', 'Out to Bid'), ('BIDS_RECEIVED', 'Bids Received'), ('SUBCONTRACT_ISSUED', 'Subcontract Issued')], default='NOT_STARTED', max_length=25)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trades', to=settings.AUTH_USER_MODEL)),
                ('csi_trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='core.csitrade')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'csi_trade__csi_code'],
                'constraints': [models.UniqueConstraint(fields=('project', 'csi_trade'), name='unique_trade_per_project')],
            },
        ),
    ]
