# Generated by Django 5.2 on 2026-03-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DRAFTING', 'Drafting'), ('OUT_TO_BID', 'Out to Bid'), ('BIDS_RECEIVED', 'Bids Received'), ('OWNER_REVIEW', 'Owner Review'), ('SUBCONTRACTOR_APPROVED', 'Subcontractor Approved')], default='NOT_STARTED', max_length=25),
        ),
    ]
