# Generated by Django 5.2 on 2026-03-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeitem',
            name='is_pending_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scopeitem',
            name='pending_original_text',
            field=models.TextField(blank=True),
        ),
    ]
