# Generated by Django 5.2 on 2026-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0002_add_pending_review_to_scope_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeitem',
            name='pending_delete',
            field=models.BooleanField(default=False),
        ),
    ]
