# Generated by Django 5.2 on 2026-03-04 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('note_type', models.CharField(choices=[('SCOPE_CLARIFICATION', 'Scope Clarification'), ('OPEN_QUESTION', 'Open Question'), ('MEANS_METHODS', 'Means & Methods'), ('OWNER_ARCHITECT_DIRECTION', 'Owner/Architect Direction')], max_length=30)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=10)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('primary_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_notes', to='projects.trade')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project')),
                ('related_trades', models.ManyToManyField(blank=True, related_name='related_notes', to='projects.trade')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
