# Generated by Django 5.2 on 2026-03-04 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('exhibits', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('csi_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.csitrade')),
                ('project_type_tags', models.ManyToManyField(blank=True, related_name='checklist_items', to='core.projecttype')),
                ('source_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=15)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_reviews', to=settings.AUTH_USER_MODEL)),
                ('scope_exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_reviews', to='exhibits.scopeexhibit')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('OPEN_NOTE', 'Open Note'), ('CROSS_TRADE', 'Cross-Trade'), ('CUSTOM_CHECKLIST', 'Custom Checklist')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('WARNING', 'Warning'), ('FAIL', 'Fail')], max_length=10)),
                ('pm_response', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('final_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reviews.finalreview')),
            ],
        ),
    ]
