# Generated by Django 5.2 on 2026-03-08 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('SCOPE_FROM_DESCRIPTION', 'Scope from Description'), ('SCOPE_ITEM', 'Scope Item')], max_length=30)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exhibit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to='exhibits.scopeexhibit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
