# Generated by Django 5.2 on 2026-03-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_add_request_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequestlog',
            name='request_type',
            field=models.CharField(choices=[('SCOPE_FROM_DESCRIPTION', 'Scope from Description'), ('SCOPE_ITEM', 'Scope Item'), ('REWRITE_ITEM', 'Rewrite Item'), ('EXPAND_ITEM', 'Expand Item'), ('CHAT', 'Chat'), ('COMPLETENESS_CHECK', 'Completeness Check')], max_length=30),
        ),
    ]
