# Generated by Django 5.2 on 2026-03-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0004_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='changes_applied_pks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
