# Generated by Django 5.2 on 2026-03-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0005_add_changes_applied_pks_to_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequestlog',
            name='request_type',
            field=models.CharField(choices=[('SCOPE_FROM_DESCRIPTION', 'Scope from Description'), ('SCOPE_ITEM', 'Scope Item'), ('REWRITE_ITEM', 'Rewrite Item'), ('EXPAND_ITEM', 'Expand Item'), ('CHAT', 'Chat'), ('COMPLETENESS_CHECK', 'Completeness Check'), ('REWRITE_SECTION', 'Rewrite Section'), ('NOTE_TO_SCOPE', 'Note to Scope')], max_length=30),
        ),
    ]
