# Generated by Django 5.2 on 2026-03-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0006_add_rewrite_section_and_note_to_scope_request_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
